#!/usr/bin/env node
const express = require('express');
const port = process.env.PORT || 3000;

const app = express();
app.use(express.static(`${__dirname}/public`));
app.listen(port, _ => {
  console.log(`Express server listening on port \x1b[32m${port}\x1b[0m ...\n`);
});
