#!/bin/bash
if hash ruby 2>/dev/null; then
  ruby -run -ehttpd . -p8000
elif hash python3 2>/dev/null; then
  python3 -m http.server 8000
elif hash python2 2>/dev/null; then
  python2 -m SimpleHTTPServer 8000
else
  echo 'No python!'
fi
